[package]
name = "ac-server-workers"
version = "0.3.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { workspace = true, features = ["http", "axum"] }
tower = { workspace = true }
axum = { version = "0.8", default-features = false }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
