[package]
name = "ac-api"
version = "0.3.0"
edition = "2024"
license.workspace = true

[dependencies]
ac-types = { path = "../ac-types" }
ac-crypto = { path = "../ac-crypto" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
