[package]
name = "ac-db"
version = "0.1.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"

[dependencies]
sqlx = { workspace = true }
ac-types = { path = "../ac-types" }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
