[package]
name = "ac-runtime"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
axum = { workspace = true }
tower = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1"
lambda_http = { version = "1", optional = true }
lambda_runtime = { version = "1", optional = true }
http = { workspace = true }
tokio = { workspace = true }
bytes = "1"
http-body-util = "0.1"
tracing = { workspace = true }
worker = { version = "0.8.5", features = ["axum"], optional = true }

[features]
lambda = ["dep:lambda_http", "dep:lambda_runtime"]
cloudrun = []
workers = ["dep:worker"]

[dev-dependencies]
futures = "0.3"
tokio = { workspace = true, features = ["macros", "rt"] }
