[package]
name = "ac-runtime"
version = "0.3.0"
edition = "2024"
license.workspace = true

[dependencies]
axum = { workspace = true }
tower = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
lambda_http = { workspace = true, optional = true }
lambda_runtime = { workspace = true, optional = true }
http = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
http-body-util = { workspace = true }
tracing = { workspace = true }
worker = { workspace = true, features = ["axum"], optional = true }

[features]
lambda = ["dep:lambda_http", "dep:lambda_runtime"]
cloudrun = []
workers = ["dep:worker"]

[dev-dependencies]
futures = "0.3"
tokio = { workspace = true, features = ["macros", "rt"] }
